"""Add tenant_id fields to enterprise models

Revision ID: 1a70c150d786
Revises: 7d4837812552
Create Date: 2025-08-17 13:26:27.991991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a70c150d786'
down_revision = '7d4837812552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_approval_workflows', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leave_approval_workflows_tenant_id'), 'leave_approval_workflows', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leave_approval_workflows', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('leave_balances', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leave_balances_tenant_id'), 'leave_balances', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leave_balances', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('leave_calendars', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leave_calendars_tenant_id'), 'leave_calendars', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leave_calendars', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('leave_notifications', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leave_notifications_tenant_id'), 'leave_notifications', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leave_notifications', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('leave_policies', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leave_policies_tenant_id'), 'leave_policies', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leave_policies', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('leave_requests', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leave_requests_tenant_id'), 'leave_requests', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leave_requests', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('payroll_audit_logs', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_payroll_audit_logs_tenant_id'), 'payroll_audit_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'payroll_audit_logs', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('payroll_entries', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_payroll_entries_tenant_id'), 'payroll_entries', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'payroll_entries', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('payroll_runs', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_payroll_runs_tenant_id'), 'payroll_runs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'payroll_runs', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('performance_feedback', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_performance_feedback_tenant_id'), 'performance_feedback', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'performance_feedback', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('performance_goals', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_performance_goals_tenant_id'), 'performance_goals', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'performance_goals', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('performance_metrics', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_performance_metrics_tenant_id'), 'performance_metrics', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'performance_metrics', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.add_column('performance_reviews', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_performance_reviews_tenant_id'), 'performance_reviews', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'performance_reviews', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('plan_features_plan_id_fkey'), 'plan_features', type_='foreignkey')
    op.create_foreign_key(None, 'plan_features', 'subscription_plans', ['plan_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('salary_structures', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_salary_structures_tenant_id'), 'salary_structures', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'salary_structures', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('tenant_billing_invoices_tenant_id_fkey'), 'tenant_billing_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_billing_invoices', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tenant_subscription_history_tenant_id_fkey'), 'tenant_subscription_history', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_subscription_history', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tenant_usage_logs_tenant_id_fkey'), 'tenant_usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_usage_logs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tenants_subscription_plan_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'subscription_plans', ['subscription_plan_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenants', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_subscription_plan_id_fkey'), 'tenants', 'subscription_plans', ['subscription_plan_id'], ['id'])
    op.drop_constraint(None, 'tenant_usage_logs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_usage_logs_tenant_id_fkey'), 'tenant_usage_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_subscription_history', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_subscription_history_tenant_id_fkey'), 'tenant_subscription_history', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_billing_invoices', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_billing_invoices_tenant_id_fkey'), 'tenant_billing_invoices', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'salary_structures', type_='foreignkey')
    op.drop_index(op.f('ix_salary_structures_tenant_id'), table_name='salary_structures')
    op.drop_column('salary_structures', 'tenant_id')
    op.drop_constraint(None, 'plan_features', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('plan_features_plan_id_fkey'), 'plan_features', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'performance_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_performance_reviews_tenant_id'), table_name='performance_reviews')
    op.drop_column('performance_reviews', 'tenant_id')
    op.drop_constraint(None, 'performance_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_performance_metrics_tenant_id'), table_name='performance_metrics')
    op.drop_column('performance_metrics', 'tenant_id')
    op.drop_constraint(None, 'performance_goals', type_='foreignkey')
    op.drop_index(op.f('ix_performance_goals_tenant_id'), table_name='performance_goals')
    op.drop_column('performance_goals', 'tenant_id')
    op.drop_constraint(None, 'performance_feedback', type_='foreignkey')
    op.drop_index(op.f('ix_performance_feedback_tenant_id'), table_name='performance_feedback')
    op.drop_column('performance_feedback', 'tenant_id')
    op.drop_constraint(None, 'payroll_runs', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_runs_tenant_id'), table_name='payroll_runs')
    op.drop_column('payroll_runs', 'tenant_id')
    op.drop_constraint(None, 'payroll_entries', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_entries_tenant_id'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'tenant_id')
    op.drop_constraint(None, 'payroll_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_audit_logs_tenant_id'), table_name='payroll_audit_logs')
    op.drop_column('payroll_audit_logs', 'tenant_id')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_index(op.f('ix_leave_requests_tenant_id'), table_name='leave_requests')
    op.drop_column('leave_requests', 'tenant_id')
    op.drop_constraint(None, 'leave_policies', type_='foreignkey')
    op.drop_index(op.f('ix_leave_policies_tenant_id'), table_name='leave_policies')
    op.drop_column('leave_policies', 'tenant_id')
    op.drop_constraint(None, 'leave_notifications', type_='foreignkey')
    op.drop_index(op.f('ix_leave_notifications_tenant_id'), table_name='leave_notifications')
    op.drop_column('leave_notifications', 'tenant_id')
    op.drop_constraint(None, 'leave_calendars', type_='foreignkey')
    op.drop_index(op.f('ix_leave_calendars_tenant_id'), table_name='leave_calendars')
    op.drop_column('leave_calendars', 'tenant_id')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_index(op.f('ix_leave_balances_tenant_id'), table_name='leave_balances')
    op.drop_column('leave_balances', 'tenant_id')
    op.drop_constraint(None, 'leave_approval_workflows', type_='foreignkey')
    op.drop_index(op.f('ix_leave_approval_workflows_tenant_id'), table_name='leave_approval_workflows')
    op.drop_column('leave_approval_workflows', 'tenant_id')
    # ### end Alembic commands ###
